apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.name }}
  labels:
    app: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  type: ClusterIP
  ports:
    - port: ${{ values.port }}
      targetPort: ${{ values.port }}
      protocol: TCP
      name: http
  selector:
    app: ${{ values.name }}
